version: '3.1'

networks:
  proxy:
    external: true
    name: proxy
  internal:

volumes:
  db:
  data:

services:
  wordpress:
    image: wordpress
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - data:/var/www/html
      - /home/nico/queerreferat_ac/wordpress/plugins:/var/www/html/wp-content/plugins
      - /home/nico/queerreferat_ac/wordpress/themes:/var/www/html/wp-content/themes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`queerreferat.ac`, `www.queerreferat.ac`)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://queerreferat\\.ac/?(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.queerreferat.ac/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
      - "traefik.http.routers.wordpress.middlewares=redirect-to-www,wordpress-authentik"
      - "traefik.http.middlewares.wordpress-authentik.forwardauth.address=http://authentik-server-1:9000/outpost.goauthentik.io/auth/traefik"
      # allow our scraping without requiring auth via authentik
      # based on https://github.com/goauthentik/authentik/issues/2029#issuecomment-1008365610
      - "traefik.http.routers.wordpress-noauth.rule=Host(`www.queerreferat.ac`) && ( ClientIP(`157.90.119.62`) || ClientIP(`2a01:4f8:c2c:5535::1`))"
    networks:
      - proxy
      - internal
    env_file:
      - .env

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal
    env_file:
      - .env

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 8084:80
  #   networks:
  #     - internal
  #     - proxy
